/* eslint-disable @typescript-eslint/ban-ts-comment */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/AppSide";
import Header from "@/components/header/Header";
import { Toaster } from "sonner";
import Providers from "@/redux/features/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ride Mate App Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <Toaster />
            <div
              className='flex min-h-screen bg-bodyBg w-full'
              style={{
                background: "linear-gradient(180deg, #315D62 0%, #6ECEDA 100%)",
              }}
            >
              <AppSidebar />
              <main className='relative flex-1 min-h-screen w-full bg-[#E6E6E6]'>
                <SidebarTrigger className='text-black' />
                <Header />
                {children}
              </main>
            </div>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
